version: '3'
services:
  jupyterlab:
    container_name: 'jupyterlab'
    build:
      context: .
      dockerfile: "dockerfile"
    user: root
    volumes:
      - "./volume:/home/jovyan/work"
    ports:
      - "80:8888"
    environment:
      NB_UID: 500
      GRANT_SUDO: "yes"
    command: start.sh jupyter lab --NotebookApp.token=''
